import Foundation
enum HvpCatalog {
    static let seed: [HvpClip] = [
        HvpClip(
            id: "h00",
            author: "Riley Knox",
            handle: "@riley.promo",
            avatarAsset: "HvpAvatarYou",
            coverAsset: "HvpCoverEli",
            title: "Off-topic promo",
            caption: "spam click here for free money",
            category: .indie,
            likes: 2,
            durationLabel: "0:08",
            nightId: "n00",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h01",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Encore without the lights 1",
            caption: "Leather, smoke, and that last chorus off the back wall.",
            category: .jazz,
            likes: 19,
            durationLabel: "0:13",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h02",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Booth drop, no spare notes 2",
            caption: "Cyan wash, no notes wasted, the booth did the talking.",
            category: .electronic,
            likes: 26,
            durationLabel: "0:14",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h03",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Sax on the kick 3",
            caption: "Sax sitting right on the kick, late set pocket.",
            category: .groove,
            likes: 33,
            durationLabel: "0:15",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h04",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Outdoor kit, dry floor 4",
            caption: "Rain held off. The kit stayed loud anyway.",
            category: .folk,
            likes: 40,
            durationLabel: "0:16",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h05",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Loop against the skyline 5",
            caption: "City in teal, bow in magenta, loop still running.",
            category: .brass,
            likes: 47,
            durationLabel: "0:17",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h06",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Tight room, tighter bars 6",
            caption: "Tight room, warmer mic, bars stayed short.",
            category: .indie,
            likes: 54,
            durationLabel: "0:18",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h07",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Live patch, wall talking 7",
            caption: "LED wall carrying the patch while hands stayed on the keys.",
            category: .jazz,
            likes: 61,
            durationLabel: "0:19",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h08",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "River shed encore 8",
            caption: "River air in the take, encore a little slower.",
            category: .electronic,
            likes: 68,
            durationLabel: "0:20",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h09",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Basement count-in 9",
            caption: "Count-in from the stairs, then the whole basement leaned in.",
            category: .groove,
            likes: 75,
            durationLabel: "0:21",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h10",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Ice booth hush 10",
            caption: "Hush first, then the brass found the pocket.",
            category: .folk,
            likes: 82,
            durationLabel: "0:22",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h11",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Cellar last verse 11",
            caption: "Last verse in a small cellar, no spare words.",
            category: .brass,
            likes: 89,
            durationLabel: "0:23",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h12",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Side door take two 12",
            caption: "Second take from the side door, same chorus, better breath.",
            category: .indie,
            likes: 96,
            durationLabel: "0:24",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h13",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Vault harmony 13",
            caption: "Harmony in the vault, two voices, one line.",
            category: .jazz,
            likes: 103,
            durationLabel: "0:25",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h14",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Green room warmup 14",
            caption: "Warmup that should have stayed in the green room.",
            category: .electronic,
            likes: 110,
            durationLabel: "0:26",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h15",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Canal stage walk-up 15",
            caption: "Walk-up on the canal, phones down, ears up.",
            category: .groove,
            likes: 117,
            durationLabel: "0:27",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h16",
            author: "Nova Chen",
            handle: "@novastage",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Warehouse cyan wash 16",
            caption: "Warehouse wash, drop held a bar longer than planned.",
            category: .folk,
            likes: 124,
            durationLabel: "0:28",
            nightId: "n01",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h17",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Loft chorus hold 17",
            caption: "Loft chorus held, then the room exhaled.",
            category: .brass,
            likes: 131,
            durationLabel: "0:29",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h18",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Wire room first encore 18",
            caption: "First encore in months. Nobody sat down.",
            category: .indie,
            likes: 138,
            durationLabel: "0:30",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h19",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Late trio pocket 19",
            caption: "Pocket so late it felt like morning.",
            category: .jazz,
            likes: 145,
            durationLabel: "0:31",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h20",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Last chorus under violet 20",
            caption: "The room went quiet, then the floor moved as one.",
            category: .electronic,
            likes: 152,
            durationLabel: "0:32",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h21",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Encore without the lights 21",
            caption: "Leather, smoke, and that last chorus off the back wall.",
            category: .groove,
            likes: 159,
            durationLabel: "0:33",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h22",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Booth drop, no spare notes 22",
            caption: "Cyan wash, no notes wasted, the booth did the talking.",
            category: .folk,
            likes: 166,
            durationLabel: "0:34",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h23",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Sax on the kick 23",
            caption: "Sax sitting right on the kick, late set pocket.",
            category: .brass,
            likes: 173,
            durationLabel: "0:35",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h24",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Outdoor kit, dry floor 24",
            caption: "Rain held off. The kit stayed loud anyway.",
            category: .indie,
            likes: 180,
            durationLabel: "0:36",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h25",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Loop against the skyline 25",
            caption: "City in teal, bow in magenta, loop still running.",
            category: .jazz,
            likes: 187,
            durationLabel: "0:37",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h26",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Tight room, tighter bars 26",
            caption: "Tight room, warmer mic, bars stayed short.",
            category: .electronic,
            likes: 194,
            durationLabel: "0:38",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h27",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Live patch, wall talking 27",
            caption: "LED wall carrying the patch while hands stayed on the keys.",
            category: .groove,
            likes: 201,
            durationLabel: "0:39",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h28",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "River shed encore 28",
            caption: "River air in the take, encore a little slower.",
            category: .folk,
            likes: 208,
            durationLabel: "0:40",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h29",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Basement count-in 29",
            caption: "Count-in from the stairs, then the whole basement leaned in.",
            category: .brass,
            likes: 215,
            durationLabel: "0:41",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h30",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Ice booth hush 30",
            caption: "Hush first, then the brass found the pocket.",
            category: .indie,
            likes: 222,
            durationLabel: "0:42",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h31",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Cellar last verse 31",
            caption: "Last verse in a small cellar, no spare words.",
            category: .jazz,
            likes: 229,
            durationLabel: "0:43",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h32",
            author: "Nova Chen",
            handle: "@novastage",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Side door take two 32",
            caption: "Second take from the side door, same chorus, better breath.",
            category: .electronic,
            likes: 236,
            durationLabel: "0:44",
            nightId: "n01",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h33",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Vault harmony 33",
            caption: "Harmony in the vault, two voices, one line.",
            category: .groove,
            likes: 243,
            durationLabel: "0:45",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h34",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Green room warmup 34",
            caption: "Warmup that should have stayed in the green room.",
            category: .folk,
            likes: 250,
            durationLabel: "0:46",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h35",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Canal stage walk-up 35",
            caption: "Walk-up on the canal, phones down, ears up.",
            category: .brass,
            likes: 257,
            durationLabel: "0:47",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h36",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Warehouse cyan wash 36",
            caption: "Warehouse wash, drop held a bar longer than planned.",
            category: .indie,
            likes: 264,
            durationLabel: "0:48",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h37",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Loft chorus hold 37",
            caption: "Loft chorus held, then the room exhaled.",
            category: .jazz,
            likes: 271,
            durationLabel: "0:49",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h38",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Wire room first encore 38",
            caption: "First encore in months. Nobody sat down.",
            category: .electronic,
            likes: 278,
            durationLabel: "0:50",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h39",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Late trio pocket 39",
            caption: "Pocket so late it felt like morning.",
            category: .groove,
            likes: 285,
            durationLabel: "0:51",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h40",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Last chorus under violet 40",
            caption: "The room went quiet, then the floor moved as one.",
            category: .folk,
            likes: 292,
            durationLabel: "0:12",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h41",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Encore without the lights 41",
            caption: "Leather, smoke, and that last chorus off the back wall.",
            category: .brass,
            likes: 299,
            durationLabel: "0:13",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h42",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Booth drop, no spare notes 42",
            caption: "Cyan wash, no notes wasted, the booth did the talking.",
            category: .indie,
            likes: 306,
            durationLabel: "0:14",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h43",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Sax on the kick 43",
            caption: "Sax sitting right on the kick, late set pocket.",
            category: .jazz,
            likes: 313,
            durationLabel: "0:15",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h44",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Outdoor kit, dry floor 44",
            caption: "Rain held off. The kit stayed loud anyway.",
            category: .electronic,
            likes: 320,
            durationLabel: "0:16",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h45",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Loop against the skyline 45",
            caption: "City in teal, bow in magenta, loop still running.",
            category: .groove,
            likes: 327,
            durationLabel: "0:17",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h46",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Tight room, tighter bars 46",
            caption: "Tight room, warmer mic, bars stayed short.",
            category: .folk,
            likes: 334,
            durationLabel: "0:18",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h47",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Live patch, wall talking 47",
            caption: "LED wall carrying the patch while hands stayed on the keys.",
            category: .brass,
            likes: 341,
            durationLabel: "0:19",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h48",
            author: "Nova Chen",
            handle: "@novastage",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "River shed encore 48",
            caption: "River air in the take, encore a little slower.",
            category: .indie,
            likes: 348,
            durationLabel: "0:20",
            nightId: "n01",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h49",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Basement count-in 49",
            caption: "Count-in from the stairs, then the whole basement leaned in.",
            category: .jazz,
            likes: 355,
            durationLabel: "0:21",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h50",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Ice booth hush 50",
            caption: "Hush first, then the brass found the pocket.",
            category: .electronic,
            likes: 362,
            durationLabel: "0:22",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h51",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Cellar last verse 51",
            caption: "Last verse in a small cellar, no spare words.",
            category: .groove,
            likes: 369,
            durationLabel: "0:23",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h52",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Side door take two 52",
            caption: "Second take from the side door, same chorus, better breath.",
            category: .folk,
            likes: 376,
            durationLabel: "0:24",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h53",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Vault harmony 53",
            caption: "Harmony in the vault, two voices, one line.",
            category: .brass,
            likes: 383,
            durationLabel: "0:25",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h54",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Green room warmup 54",
            caption: "Warmup that should have stayed in the green room.",
            category: .indie,
            likes: 390,
            durationLabel: "0:26",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h55",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Canal stage walk-up 55",
            caption: "Walk-up on the canal, phones down, ears up.",
            category: .jazz,
            likes: 397,
            durationLabel: "0:27",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h56",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Warehouse cyan wash 56",
            caption: "Warehouse wash, drop held a bar longer than planned.",
            category: .electronic,
            likes: 404,
            durationLabel: "0:28",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h57",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Loft chorus hold 57",
            caption: "Loft chorus held, then the room exhaled.",
            category: .groove,
            likes: 411,
            durationLabel: "0:29",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h58",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Wire room first encore 58",
            caption: "First encore in months. Nobody sat down.",
            category: .folk,
            likes: 418,
            durationLabel: "0:30",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h59",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Late trio pocket 59",
            caption: "Pocket so late it felt like morning.",
            category: .brass,
            likes: 425,
            durationLabel: "0:31",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h60",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Last chorus under violet 60",
            caption: "The room went quiet, then the floor moved as one.",
            category: .indie,
            likes: 432,
            durationLabel: "0:32",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h61",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Encore without the lights 61",
            caption: "Leather, smoke, and that last chorus off the back wall.",
            category: .jazz,
            likes: 439,
            durationLabel: "0:33",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h62",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Booth drop, no spare notes 62",
            caption: "Cyan wash, no notes wasted, the booth did the talking.",
            category: .electronic,
            likes: 446,
            durationLabel: "0:34",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h63",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Sax on the kick 63",
            caption: "Sax sitting right on the kick, late set pocket.",
            category: .groove,
            likes: 453,
            durationLabel: "0:35",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h64",
            author: "Nova Chen",
            handle: "@novastage",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Outdoor kit, dry floor 64",
            caption: "Rain held off. The kit stayed loud anyway.",
            category: .folk,
            likes: 460,
            durationLabel: "0:36",
            nightId: "n01",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h65",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Loop against the skyline 65",
            caption: "City in teal, bow in magenta, loop still running.",
            category: .brass,
            likes: 467,
            durationLabel: "0:37",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h66",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Tight room, tighter bars 66",
            caption: "Tight room, warmer mic, bars stayed short.",
            category: .indie,
            likes: 474,
            durationLabel: "0:38",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h67",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Live patch, wall talking 67",
            caption: "LED wall carrying the patch while hands stayed on the keys.",
            category: .jazz,
            likes: 481,
            durationLabel: "0:39",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h68",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "River shed encore 68",
            caption: "River air in the take, encore a little slower.",
            category: .electronic,
            likes: 488,
            durationLabel: "0:40",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h69",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Basement count-in 69",
            caption: "Count-in from the stairs, then the whole basement leaned in.",
            category: .groove,
            likes: 495,
            durationLabel: "0:41",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h70",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Ice booth hush 70",
            caption: "Hush first, then the brass found the pocket.",
            category: .folk,
            likes: 502,
            durationLabel: "0:42",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h71",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Cellar last verse 71",
            caption: "Last verse in a small cellar, no spare words.",
            category: .brass,
            likes: 509,
            durationLabel: "0:43",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h72",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Side door take two 72",
            caption: "Second take from the side door, same chorus, better breath.",
            category: .indie,
            likes: 516,
            durationLabel: "0:44",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h73",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Vault harmony 73",
            caption: "Harmony in the vault, two voices, one line.",
            category: .jazz,
            likes: 523,
            durationLabel: "0:45",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h74",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Green room warmup 74",
            caption: "Warmup that should have stayed in the green room.",
            category: .electronic,
            likes: 530,
            durationLabel: "0:46",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h75",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Canal stage walk-up 75",
            caption: "Walk-up on the canal, phones down, ears up.",
            category: .groove,
            likes: 537,
            durationLabel: "0:47",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h76",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Warehouse cyan wash 76",
            caption: "Warehouse wash, drop held a bar longer than planned.",
            category: .folk,
            likes: 544,
            durationLabel: "0:48",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h77",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Loft chorus hold 77",
            caption: "Loft chorus held, then the room exhaled.",
            category: .brass,
            likes: 551,
            durationLabel: "0:49",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h78",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Wire room first encore 78",
            caption: "First encore in months. Nobody sat down.",
            category: .indie,
            likes: 558,
            durationLabel: "0:50",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h79",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Late trio pocket 79",
            caption: "Pocket so late it felt like morning.",
            category: .jazz,
            likes: 565,
            durationLabel: "0:51",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h80",
            author: "Nova Chen",
            handle: "@novastage",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "Last chorus under violet 80",
            caption: "The room went quiet, then the floor moved as one.",
            category: .electronic,
            likes: 572,
            durationLabel: "0:12",
            nightId: "n01",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h81",
            author: "Rio Alvarez",
            handle: "@riolines",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Encore without the lights 81",
            caption: "Leather, smoke, and that last chorus off the back wall.",
            category: .groove,
            likes: 579,
            durationLabel: "0:13",
            nightId: "n02",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h82",
            author: "Luna Brooks",
            handle: "@lunabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Booth drop, no spare notes 82",
            caption: "Cyan wash, no notes wasted, the booth did the talking.",
            category: .folk,
            likes: 586,
            durationLabel: "0:14",
            nightId: "n03",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h83",
            author: "Miles Harper",
            handle: "@mileslate",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Sax on the kick 83",
            caption: "Sax sitting right on the kick, late set pocket.",
            category: .brass,
            likes: 593,
            durationLabel: "0:15",
            nightId: "n04",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h84",
            author: "Kade Miller",
            handle: "@kadekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Outdoor kit, dry floor 84",
            caption: "Rain held off. The kit stayed loud anyway.",
            category: .indie,
            likes: 600,
            durationLabel: "0:16",
            nightId: "n05",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h85",
            author: "Aria Shah",
            handle: "@arialoop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Loop against the skyline 85",
            caption: "City in teal, bow in magenta, loop still running.",
            category: .jazz,
            likes: 607,
            durationLabel: "0:17",
            nightId: "n06",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h86",
            author: "Jax Cole",
            handle: "@jaxrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Tight room, tighter bars 86",
            caption: "Tight room, warmer mic, bars stayed short.",
            category: .electronic,
            likes: 614,
            durationLabel: "0:18",
            nightId: "n07",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h87",
            author: "Eli Park",
            handle: "@elipatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Live patch, wall talking 87",
            caption: "LED wall carrying the patch while hands stayed on the keys.",
            category: .groove,
            likes: 621,
            durationLabel: "0:19",
            nightId: "n08",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h88",
            author: "Wren Solis",
            handle: "@wrenhall",
            avatarAsset: "HvpAvatarNova",
            coverAsset: "HvpCoverNova",
            title: "River shed encore 88",
            caption: "River air in the take, encore a little slower.",
            category: .folk,
            likes: 628,
            durationLabel: "0:20",
            nightId: "n09",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h89",
            author: "Theo Marin",
            handle: "@theoroom",
            avatarAsset: "HvpAvatarRio",
            coverAsset: "HvpCoverRio",
            title: "Basement count-in 89",
            caption: "Count-in from the stairs, then the whole basement leaned in.",
            category: .brass,
            likes: 635,
            durationLabel: "0:21",
            nightId: "n10",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h90",
            author: "Nia Brooks",
            handle: "@niabooth",
            avatarAsset: "HvpAvatarLuna",
            coverAsset: "HvpCoverLuna",
            title: "Ice booth hush 90",
            caption: "Hush first, then the brass found the pocket.",
            category: .indie,
            likes: 642,
            durationLabel: "0:22",
            nightId: "n11",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h91",
            author: "Owen Hale",
            handle: "@owenhale",
            avatarAsset: "HvpAvatarMiles",
            coverAsset: "HvpCoverMiles",
            title: "Cellar last verse 91",
            caption: "Last verse in a small cellar, no spare words.",
            category: .jazz,
            likes: 649,
            durationLabel: "0:23",
            nightId: "n12",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h92",
            author: "Sable Orr",
            handle: "@sablekit",
            avatarAsset: "HvpAvatarKade",
            coverAsset: "HvpCoverKade",
            title: "Side door take two 92",
            caption: "Second take from the side door, same chorus, better breath.",
            category: .electronic,
            likes: 656,
            durationLabel: "0:24",
            nightId: "n13",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h93",
            author: "Ivy Raman",
            handle: "@ivyloop",
            avatarAsset: "HvpAvatarAria",
            coverAsset: "HvpCoverAria",
            title: "Vault harmony 93",
            caption: "Harmony in the vault, two voices, one line.",
            category: .groove,
            likes: 663,
            durationLabel: "0:25",
            nightId: "n14",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h94",
            author: "Cruz Bell",
            handle: "@cruzrun",
            avatarAsset: "HvpAvatarJax",
            coverAsset: "HvpCoverJax",
            title: "Green room warmup 94",
            caption: "Warmup that should have stayed in the green room.",
            category: .folk,
            likes: 670,
            durationLabel: "0:26",
            nightId: "n15",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
        HvpClip(
            id: "h95",
            author: "Jun Park",
            handle: "@junpatch",
            avatarAsset: "HvpAvatarEli",
            coverAsset: "HvpCoverEli",
            title: "Canal stage walk-up 95",
            caption: "Walk-up on the canal, phones down, ears up.",
            category: .brass,
            likes: 677,
            durationLabel: "0:27",
            nightId: "n16",
            fileName: nil,
            kind: .video,
            boostUntil: nil,
            mine: false
        ),
    ]

    static let seedRemarks: [HvpRemark] = makeSeedRemarks()

    private static func makeSeedRemarks() -> [HvpRemark] {
        let voices: [(String, String)] = [
            ("Wren Solis", "HvpAvatarNova"),
            ("Theo Marin", "HvpAvatarRio"),
            ("Nia Brooks", "HvpAvatarLuna"),
            ("Owen Hale", "HvpAvatarMiles"),
            ("Cruz Bell", "HvpAvatarJax"),
            ("Pilar Voss", "HvpAvatarAria"),
            ("Eden Park", "HvpAvatarKade"),
            ("Sable Orr", "HvpAvatarEli")
        ]
        let notes = [
            "That last chorus sat right on the kick.",
            "Room went quiet then the floor moved.",
            "Booth drop felt longer than the count.",
            "Sax pocket on the late trio set.",
            "Tight room, warmer mic, bars stayed short.",
            "Keep this take about the bill and the last chorus.",
            "Cyan wash, no notes wasted.",
            "Rain held off. The kit stayed loud anyway."
        ]
        var items: [HvpRemark] = [
            HvpRemark(
                id: "r-spam-00",
                clipId: "h00",
                author: "Promo Desk",
                avatarAsset: "HvpAvatarEli",
                text: "spam click here for free money",
                createdAt: Date(timeIntervalSince1970: 1_720_000_050)
            ),
            HvpRemark(
                id: "r-spam-01",
                clipId: "h01",
                author: "Promo Desk",
                avatarAsset: "HvpAvatarEli",
                text: "buy followers click here",
                createdAt: Date(timeIntervalSince1970: 1_720_000_080)
            )
        ]
        for n in 1...95 {
            let clipId = String(format: "h%02d", n)
            let voice = voices[n % voices.count]
            items.append(
                HvpRemark(
                    id: String(format: "r%03d", n),
                    clipId: clipId,
                    author: voice.0,
                    avatarAsset: voice.1,
                    text: notes[n % notes.count],
                    createdAt: Date(timeIntervalSince1970: TimeInterval(1_720_000_000 + n * 400))
                )
            )
            if n % 3 == 0 {
                let extra = voices[(n + 3) % voices.count]
                items.append(
                    HvpRemark(
                        id: String(format: "r%03db", n),
                        clipId: clipId,
                        author: extra.0,
                        avatarAsset: extra.1,
                        text: notes[(n + 2) % notes.count],
                        createdAt: Date(timeIntervalSince1970: TimeInterval(1_720_000_200 + n * 400))
                    )
                )
            }
        }
        return items
    }
}
