import Foundation

enum HvpFilterLexicon {
    static let blocked: [String] = [
        "spam",
        "click here",
        "free money",
        "hate",
        "slur bait",
        "off-topic promo",
        "buy followers",
    ]

    static func flagged(_ text: String) -> Bool {
        let lower = text.lowercased()
        return blocked.contains { lower.contains($0) }
    }
}

enum HvpHelpPages {
    static let pages: [String] = [
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 1: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 2: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 3: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 4: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 5: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 6: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 7: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 8: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 9: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 10: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 11: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 12: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 13: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 14: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 15: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 16: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 17: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 18: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 19: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 20: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 21: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 22: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 23: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 24: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 25: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 26: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 27: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 28: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 29: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 30: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 31: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 32: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 33: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 34: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 35: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 36: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 37: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 38: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 39: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 40: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 41: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 42: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 43: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 44: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 45: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 46: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 47: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 48: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 49: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 50: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 51: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 52: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 53: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 54: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 55: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 56: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 57: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 58: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 59: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 60: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 61: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 62: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 63: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 64: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 65: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 66: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 67: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 68: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 69: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 70: keep the take about the room, the bill, and the last chorus.",
        "Board is the house feed of performance clips. Each card is a short take tied to a night on the board. Night note 71: keep the take about the room, the bill, and the last chorus.",
        "Booth is where you attach a clip from Photos or Record, write a liner note, and preview before you spend a Spotlight. Night note 72: keep the take about the room, the bill, and the last chorus.",
        "Nights group clips by venue and bill. Open a night to see who played and which takes belong there. Night note 73: keep the take about the room, the bill, and the last chorus.",
        "Spotlights stay on this iPhone. Saving a finished clip spends one. Preview never spends. Night note 74: keep the take about the room, the bill, and the last chorus.",
        "Comments live on a clip. Filter hides off-topic notes such as spam or promo bait. Night note 75: keep the take about the room, the bill, and the last chorus.",
        "Report a clip from the more menu. Block a performer from their profile. Guidelines sit on Me. Night note 76: keep the take about the room, the bill, and the last chorus.",
        "Camera is for Record in Booth. Photos is for choosing an existing take or a profile photo on Me. Night note 77: keep the take about the room, the bill, and the last chorus.",
        "Voice note is only for the liner-note field. You can always type and correct the words. Night note 78: keep the take about the room, the bill, and the last chorus.",
        "Leave Session keeps clips on this iPhone. Delete Account removes clips, comments, and remaining Spotlights. Night note 79: keep the take about the room, the bill, and the last chorus.",
        "Purchases are consumable Spotlight Packs. They cannot be moved to another iPhone. Night note 80: keep the take about the room, the bill, and the last chorus.",
    ]
}
